language: node_js
script: npm run website-dist
local-dir: website/dist
before_install: npm install -g npm@latest
deploy:
  provider: pages
  fqdn: www.duxtable.com
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master
