language: node_js
node_js:
  - "lts/*"
script: npm run website-dist
deploy:
  provider: pages
  local-dir: website/dist
  fqdn: www.duxtable.com
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: stable
